function betType() {
    return [{
        id: 1,
        type: "<12k",
        count: 1680,
        transList: [{
            name: "a16z",
            id: 1,
            bet: 100
        }, {
            name: "a16z",
            id: 2,
            bet: 1000
        }, {
            name: "a16z",
            id: 3,
            bet: 230
        }, {
            name: "a16z",
            id: 4,
            bet: 160
        }, {
            name: "a16z",
            id: 5,
            bet: 290
        }]
    }, {
        id: 2,
        type: "12k-16k",
        count: 2480,
        transList: [{
            name: "a16z",
            id: 1,
            bet: 100
        }, {
            name: "a16z",
            id: 2,
            bet: 1000
        }, {
            name: "a16z",
            id: 3,
            bet: 230
        }, {
            name: "a16z",
            id: 4,
            bet: 160
        }, {
            name: "a16z",
            id: 5,
            bet: 290
        }]
    }, {
        id: 3,
        type: "16k-20k",
        count: 480,
        transList: [{
            name: "a16z",
            id: 1,
            bet: 100
        }, {
            name: "a16z",
            id: 2,
            bet: 1000
        }, {
            name: "a16z",
            id: 3,
            bet: 230
        }, {
            name: "a16z",
            id: 4,
            bet: 160
        }, {
            name: "a16z",
            id: 5,
            bet: 290
        }]
    }, {
        id: 4,
        type: ">20k",
        count: 90,
        transList: [{
            name: "a16z",
            id: 1,
            bet: 100
        }, {
            name: "a16z",
            id: 2,
            bet: 1000
        }, {
            name: "a16z",
            id: 3,
            bet: 230
        }, {
            name: "a16z",
            id: 4,
            bet: 160
        }, {
            name: "a16z",
            id: 5,
            bet: 290
        }]
    }];
}

export default betType;